from .user import router as user_router
from .training import router as training_router
from .boxing import router as boxing_router
from .kafka import router as kafka_router
from .exercise import router as exercise_router
from .consent import router as consent_router
from .hybrid_analysis import router as hybrid_analysis_router
from .gamification import router as gamification_router
from .monitoring import router as monitoring_router
